spring:
  profiles:
    active: dev # 表示开发环境
    #active: test
    #active: info
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/123?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456